//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportSeason
    {
        public int SportSeasonID { get; set; }
        public string SportSeasonStart { get; set; }
        public string SportSeasonEnd { get; set; }
    }
}
